### ISSUE TITLE
[feature] Validate model directory for the given format

### ISSUE THREAD

**Issue by gaocegege** [kleveross/ormb#11]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

We should validate the model.

Ref https://github.com/caicloud/ormb/pull/10#discussion_r429014208

/cc @codeflitting

**Comment by codeflitting** [comment]
At the same time, ORMB UI needs to visualize the model directory structure

**Comment by gaocegege** [comment]
> At the same time, ORMB UI needs to visualize the model directory structure

I think it is a separate feature, will open a new issue for it.

**Comment by gaocegege** [comment]
https://github.com/caicloud/ormb/issues/42

**Comment by simon-cj** [comment]
> /assign @simon-cj I think we also need it when uploading models in dashboard.

`validate model directory when uploading models in dashboard`, I think it should be in the model registry， not in ormb， WDYT

**Comment by gaocegege** [comment]
Yeah, I think so. But we also need to validate the model in ormb side. WDYT

**Comment by simon-cj** [comment]
I am not understant this issue, can you describe it

**Comment by gaocegege** [comment]
When users run `ormb save`, we need to validate that the model is qualified.

**Comment by simon-cj** [comment]
SGTM, I will do it
