### ISSUE TITLE
[feature] Do not require sub-directory in model if the format does not need it.

### ISSUE THREAD

**Issue by gaocegege** [kleveross/ormb#118]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

TensorFlow savedmodel has a sub-directory in the model directory like this:

```
- model
  - 1
    - saved_model.pb
    ...
```

But other formats does not need it, we should not require it in other frameworks.

As you know, TRTIS requires it, too. We can make this directory in storage initializer.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by simon-cj** [comment]
if so， the PR https://github.com/kleveross/ormb/commit/33b44e7bc1869d2372d194d70685598b1fb07f15 is not right, should keep it same as before？I misunderstanding？
accourding to this issue， including TensorFlow Savedmodel，there should not have  `1` directory.
