### ISSUE TITLE
[feature] auto create directory when export a model

### ISSUE THREAD

**Issue by tskdsb** [kleveross/ormb#146]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

**What happened**:
when I try to export a model after pulling, I got an error:
```
ormb export -d bbb 1.2.3.4:5678/test-modelset/test-modeset:v1
ref:       1.2.3.4:5678/test-modelset/test-modeset:v1
digest:    c860afd8f993a754b9910f40fb66e45005988c0e23c7470560a2dd9033843f07
size:      28.9 MiB
format:    MXNETParams
Error: open /aaa/bbb/ormbfile.yaml: no such file or directory
...
```
I can't get the reason by the message, but when I created a directory called bbb, it exports successfully. So, it needs the export-directory to exist firstly.

**What you expected to happen**:
create the directory when I run `ormb export ...` like `git clone`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I may provide a PR to solve it

**Comment by judgeeeeee** [comment]
Can you show the ‘bbb’ file directory？ @tskdsb 
Is there a ormbfile.yaml in your model path？
