### ISSUE TITLE
Broken image link in zh introduction.md

### ISSUE THREAD

**Issue by YikSanChan** [kleveross/ormb#164]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**What happened**:

In https://github.com/kleveross/ormb/blob/master/docs/docs_zh/introduction.md, the image https://github.com/kleveross/ormb/blob/master/docs/docs_zh/images/intro/harbor.png is missing

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by FogDong** [comment]
Thanks for your report!

/kind bug
/assign @FogDong
