### ISSUE TITLE
[feature] impl ormb models command

### ISSUE THREAD

**Issue by simon-cj** [kleveross/ormb#169]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind feature
 
> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
impl `ormb models` command which is like `docker images` to list localhost models.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by SolarisYan** [comment]
+1
