### ISSUE TITLE
Export command destination parameter not used without its `-d` flag

### ISSUE THREAD

**Issue by gbolmier** [kleveross/ormb#186]
/kind bug

**What happened**:

The export command isn't using the `destination` parameter when the `--destination` flag isn't specified.

**How to reproduce it (as minimally and precisely as possible)**:

```shell
ormb export <ref> <dst>
```

With `<dst>` different than `.`, which is the default.

**Anything else we need to know?**:

I'm using the python sdk which makes it quite complicated to work around the bug. I guess it'll be better to fix the root cause of the problem, but if it takes time I can submit a quick fix in the python sdk by adding the `-d` flag to the `export` wrapper function:

https://github.com/kleveross/ormb/blob/429b3924584cc35e2d573503cfb07b61c86d7c81/extern-sdk/python/ormb/api.py#L26-L29

**Comment by gaocegege** [comment]
Seems that there needs a -t by design https://github.com/kleveross/ormb/blob/master/cmd/ormb/cmd/export.go#L42

**Comment by gbolmier** [comment]
Should I just fix the python sdk command then?

```diff
  def export(ref: str, dst: str):
-    ex = Popen([join(BIN_PATH, "ormb"), "export", ref, dst]) 
+    ex = Popen([join(BIN_PATH, "ormb"), "export", ref, "-d", dst]) 
     status = ex.wait() 
     return status 
```

**Comment by gaocegege** [comment]
SGTM

Can you please open an PR?
