### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by gbolmier** [kleveross/ormb#202]
The last release (0.0.11) was done a year ago now. New commits have been made since, I think it would be nice to have a new release of both ORMB and the python sdk. Does someone have to bandwith for it?

**Comment by gaocegege** [comment]
SGTM

**Comment by gbolmier** [comment]
Seems like the [`ormb-publish`](https://github.com/kleveross/ormb/runs/4990179426?check_suite_focus=true) run failed, no binaries assets where published.

**Comment by gaocegege** [comment]
Yeah it is caused by the wrong go version I think. I will try to fix it.

**Comment by gbolmier** [comment]
Tested the new release, works like a charm! Thank you @gaocegege, would it be possible to also make a new release of the python sdk to pypi too?

**Comment by gaocegege** [comment]
SGTM. Will do it soon.

**Comment by gbolmier** [comment]
On my side, I re-implemented the `ormb.api.py` module to use `subprocess.run` instead of `subprocess.Popen` so that we can propagate shell's stderr to python . I also added exceptions handling with custom exceptions. This is what it looks like for the login command:

```python
class ORMBLoginError(Exception):
    def __init__(self, registry_name: str, username: str, stderr: str) -> None:
        msg = f"Login to {registry_name} as '{username}' failed with stderr:\n{stderr}"
        super().__init__(msg)


def login(
    hostname: str,
    username: str,
    password: str,
    registry_name: str,
) -> subprocess.CompletedProcess:
    """
    Logs in an image registry by running ORMB CLI `login` command in a subprocess.

    Args:
        hostname: Remote registry to authenticate to.
        username: Username to authenticate with.
        password: Password to authenticate with.
        registry_name: Name of the registry for error logs.

    Returns:
        The completed process.

    Raises:
        ORMBLoginError: ORMB login command process exited with a non-zero exit code.
    """
    args = [
        BIN_PATHNAME,
        "login",
        hostname,
        "--username",
        username,
        "--password-stdin",
        "--insecure",
        "False",
    ]

    try:
        return subprocess.run(
            args=args,
            capture_output=True,
            check=True,
            input=password,
            text=True,
        )
    except subprocess.CalledProcessError as e:
        raise _cli_api_exceptions.ORMBLoginError(
            registry_name=registry_name,
            username=username,
            stderr=e.stderr,
        )
```


If you want I could create a PR this weekend to enhance the `api.py` module before you make the release.

**Comment by gaocegege** [comment]
> If you want I could create a PR this weekend to enhance the api.py module before you make the release.

I think it works for me! Thanks for the PR!

**Comment by gaocegege** [comment]
https://pypi.org/project/ormb/0.1.0/

**Comment by gbolmier** [comment]
Thx @gaocegege! Tested locally 🚀
