### ISSUE TITLE
[feature] Use goreleaser to build and publish Docker images

### ISSUE THREAD

**Issue by gaocegege** [kleveross/ormb#41]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by gaocegege** [comment]
https://goreleaser.com/customization/docker/

**Comment by gaocegege** [comment]
@ddysher 

I cannot find who owns the caicloud org in DockerHub, can you help give me push access to docker.io/caicloud/ormb and docker.io/caicloud/ormb-storage-initializer?

**Comment by gaocegege** [comment]
Or should we have a separate org for ormb in DockerHub?

**Comment by ddysher** [comment]
I believe @pendoragon has access to the account.

It it's hard to coordinate, i'm fine with using a separate org in dockerhub.

**Comment by gaocegege** [comment]
OK, let's have a separate org.

**Comment by pendoragon** [comment]
do we need a docker hub org for our open source projects? the `caicloud` account is a user account and it is troublesome to convert it to an org(if even possible). we can create an org on docker hub if needed and whoever comes up with an org name other than `caicloud` is much appreciated :).

**Comment by ddysher** [comment]
@gaocegege do you have a preferred org name?

**Comment by gaocegege** [comment]
I set up a new org cleveross in Docker Hub, but I have no objection on the name.

**Comment by simon-cj** [comment]
@gaocegege  Can close this issue?

**Comment by gaocegege** [comment]
I think we can. We are using GitHub Action to do it.
