### ISSUE TITLE
[feature] Generate ormbfile.yaml for users

### ISSUE THREAD

**Issue by gaocegege** [kleveross/ormb#48]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

For these users using Python SDK, they may not want to write such a configuration file. We may need to:

- Make it optional or
- Support some parameters to generate it or
- Analyze the parameters from the model automatically.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by gaocegege** [comment]
@simon-cj Did we generate it in model registry?

**Comment by simon-cj** [comment]
If upload model by dashboard, we will generate it, but if upload model by ormb command, we won't generate the ormbfile.yaml

**Comment by gaocegege** [comment]
Yeah, I think it is what we want. Then I am going to close it.

/close
