### ISSUE TITLE
[chore] Name for the Clever community version

### ISSUE THREAD

**Issue by gaocegege** [kleveross/ormb#63]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

We cannot move the ormb and model registry to the third-party organization currently, thus we need a new repository for our open-source model registry.

The name can be os-model-registry since it is temporary, WDYT @ddysher @simon-cj @codeflitting 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ddysher** [comment]
I thought this depends on whether we want to separate model-registry to a standalone component or not?
> We cannot move the ormb and model registry to the third-party organization currently, thus we need a new repository for our open-source model registry.

**Comment by gaocegege** [comment]
I think we already come to the agreement. We will make model-registry a standalone component.

**Comment by ddysher** [comment]
LGTM for the new repository. 

Let's have an official name so later we can just move the org, without any re-naming (which is cumbersome)?
> The name can be os-model-registry since it is temporary,

**Comment by gaocegege** [comment]
One question here. 

In the future, we will also support serving and other features. Should we have the name for the whole platform now, similar to Kubeflow?

In this case, we can name the sub-projects to simple names like model-registry and so on.

**Comment by ddysher** [comment]
yeah we do....  naming is hard

**Comment by gaocegege** [comment]
/assign @ddysher 

Thanks for your contribution! :tada: :+1:

**Comment by gaocegege** [comment]
I hope we can know from the name that the platform is the community version of Caicloud Clever.

As for the model-registry, I think it could be <project-name>-model-registry, like mlflow-model-registry.

**Comment by ddysher** [comment]
![image](https://user-images.githubusercontent.com/2191361/84852885-89afcb00-b090-11ea-965a-e86677738de1.png)

**Comment by ddysher** [comment]
@gaocegege  do you want to proceed with temp name first?

I need some inspirations......

**Comment by gaocegege** [comment]
@simon-cj Do you need a new repository to store your code now?

**Comment by simon-cj** [comment]
Yes, I need a new repository recently.

**Comment by gaocegege** [comment]
@ddysher Then I think we can use temp-model-registry, WDYT

**Comment by ddysher** [comment]
lgtm

**Comment by gaocegege** [comment]
OK, I will do it soon.

**Comment by simon-cj** [comment]
@gaocegege When the new repository can be created?

**Comment by gaocegege** [comment]
Ref https://github.com/caicloud/org/pull/311

**Comment by ddysher** [comment]
we've settled to use `klever` with org name `kleveross`.
