### ISSUE TITLE
[discussion] How to choreography model's convert and extract

### ISSUE THREAD

**Issue by simon-cj** [kleveross/ormb#73]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
Should the extract python script be included in convert python script.
or run two pod in order, one running convert script, and then another running extract script.
@gaocegege WDYT

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by gaocegege** [comment]
I think we can just push the converted model to model-registry.

Then model registry will file a new CRD request to K8s to create the extraction job.

WDYT

**Comment by simon-cj** [comment]
SGTM, If so, the status of convert job and extract job will manage independently. 
And each job MUST to update ormbfile.yaml.

**Comment by gaocegege** [comment]
Yeah I think so.

**Comment by gaocegege** [comment]
I think we already solve it in model-registry.
