### ISSUE TITLE
[chore] Move to kleveross org

### ISSUE THREAD

**Issue by gaocegege** [kleveross/ormb#89]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

We have a new open GitHub organization https://github.com/kleveross for ormb and some other projects. We should have a plan about how to transfer them to that org.

Things we need to deal with:

- Decide how to gitops (Prow) https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md
- Decide how to set up GitHub org teams
- Decide how to collaborate with non-Caiclouders easily

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ddysher** [comment]
I can transfer ormb to kleveross with a click of button in GitHub, but it might require some setups.

**Comment by gaocegege** [comment]
I think we can transfer ormb, temp-model-registry, and ftlib to klever first. Then we can investigate if we should setup Prow and so on for the new org.

The name of temp-model-registry should be renamed to klever-model-registry. /cc @simon-cj 

Suggest transferring ftlib because @zw0610 is willing to help maintain it although he is not at Caicloud now.

**Comment by gaocegege** [comment]
> but it might require some setups.

temp-model-registry and ormb all require refactoring work. @simon-cj and I will handle.

**Comment by simon-cj** [comment]
> > but it might require some setups.
> 
> temp-model-registry and ormb all require refactoring work. @simon-cj and I will handle.

OK, get it, I will refactoring klever-model-registry and klever-model-operator

**Comment by ddysher** [comment]
Done!

https://github.com/kleveross

**Comment by ddysher** [comment]
/close

@gaocegege do you want to add caicloud-bot here?

**Comment by gaocegege** [comment]
We can have a separate issue for caicloud-bot.

**Comment by ddysher** [comment]
SGTM

**Comment by ddysher** [comment]
https://github.com/kleveross/community/issues/2
