### ISSUE TITLE
[feature] Documentation for ormbfile.yaml

### ISSUE THREAD

**Issue by gaocegege** [kleveross/ormb#95]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

We need doc for ormbfile.yaml.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by simon-cj** [comment]
Completed? Can close？ @FogDong @gaocegege
